name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: yarn test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
