name: Release package to Github Packages

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: yarn version
        run: yarn version --no-git-tag-version --new-version ${{ github.event.release.tag_name }}
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: git push package.json
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add package.json
          git commit -m "chore(release): set version to ${{ github.event.release.tag_name }}"
          git push
